In [1]:
import numpy as np

a = np.random.random((1,4))
print(a)
norm = np.linalg.norm(a)
print(norm)
print(a / norm)


[[0.721519   0.72382378 0.37391849 0.43152945]]
1.170702024343539
[[0.61631311 0.61828182 0.3193968  0.36860742]]


In [9]:
W = np.random.random((2, 3))
print(W)
print()
for n in range(W.shape[1]):
    col = W[:,n]
    print(col)
    norm = np.linalg.norm(col)
    print(norm)
    W[:,n] *= norm
print()
print(W)

[[0.86432159 0.12505716 0.11375255]
 [0.44882009 0.83532154 0.71904412]]

[0.86432159 0.44882009]
0.9739051696930012
[0.12505716 0.83532154]
0.8446309093029957
[0.11375255 0.71904412]
0.7279863249953887

[[0.84176726 0.10562714 0.0828103 ]
 [0.4371082  0.70553839 0.52345429]]


In [84]:
W = np.random.normal(loc=0, scale=1,size=(2,2))
for c in range(W.shape[1]):
    col = W[:,c]
    norm = np.linalg.norm(col)
    W[:,c] /= norm

vec = np.random.random((1,2))   # o o

pred = np.dot(vec,W)            # . .
targ = np.random.random((1,2))  # o o
err = targ - pred               # - -

print("\n---")
print(f"v{vec}")
print(f"W{W}")
print(f"p{pred}")
print(f"e{err}")
print(f"t{targ}")
print("---\n")




---
v[[0.45666912 0.57435132]]
W[[ 0.83256139 -0.21057155]
 [ 0.55393278 -0.97757845]]
p[[ 0.6983571 -0.657635 ]]
e[[-0.15887863  1.09508022]]
t[[0.53947847 0.43744522]]
---



In [267]:

dW = np.outer(vec,err) * 0.05
W += dW
# print(dW)
pred = np.dot(vec,W)            # . .
err = targ - pred               # - -

print("\n---")
print(f"v{vec}")
print(f"W{W}")
print(f"p{pred}")
print(f"e{err}")
print(f"t{targ}")
print("---\n")





---
v[[0.45666912 0.57435132]]
W[[0.69872091 0.7119318 ]
 [0.38560203 0.18265112]]
p[[0.54055529 0.43002318]]
e[[-0.00107682  0.00742204]]
t[[0.53947847 0.43744522]]
---

